Increment-3
DmitryKhitrin/alerting-service pull request #3
Opened 2022-03-27 22:43 UTC by DmitryKhitrin

2022-04-03 21:27 UTC, DmitryKhitrin commented on internal/server/server.go
> +	})
Я так и не понял на самом деле как правильно делать DI в go,  вообще 0 идей, если вы сможете подсказать, то будет супер(

2022-04-03 21:28 UTC, DmitryKhitrin commented on internal/server/service/metrics/metrics.go
> +			return
Как обычно такое в go проворачивают без дженериков, но и без копипасты?

2022-04-03 21:28 UTC, DmitryKhitrin commented on internal/server/repositories/hashDb.go
> +}
Вот это как будто тоже дженериком и кастом к строке решается(

2022-04-17 20:33 UTC, blattaria7 commented on internal/server/handlers/handlers.go
> +func StatusNotImplemented(w http.ResponseWriter, _ *http.Request) {
метод описан и не используется, не хорошо) надо инициализировать)

2022-04-17 21:26 UTC, blattaria7 requested changes
Задание выполнено, тесты проходят - это шикарно) (отдельный 👍 за chi)
Мне очень понравилось как ты пишешь код, он выглядит лаконично и просто (в go мы очень стараемся следить за минимализмом и читаемостью). 
А еще ты отлично реализовал юниты!

Но необходимо внести правки, которые я оставила в комментариях к PR. Сейчас их много, но по опыту скажу, что лучше вначале побольше поработать над архитектурой и логикой, чем потом пытаться исправлять ее, добавляя новые фичи.
Если что-то будет не понятно - ставь 1-1, разберемся)

2022-04-17 21:26 UTC, blacknoire7 commented on internal/server/handlers/handlers.go
> +func StatusNotImplemented(w http.ResponseWriter, _ *http.Request) {
метод описан и не используется, не хорошо) надо инициализировать)

2022-04-17 21:26 UTC, blacknoire7 commented on internal/server/repositories/hashDb.go
>  var storageMutex = &sync.RWMutex{}
мьютексы надо определять внутри структур, для которых они создаются)  И внутри структуры помещать выше тех полей, доступ к которым он будет защищать) подробнее о практиках использования мьютексов рекомендую почитать [вот тут](https://habr.com/ru/post/271789/ ) )

2022-04-17 21:26 UTC, blattaria7 commented on internal/server/service/metrics/metrics.go
> +type Ctx struct {
не стоит называть эту структуру именем `ctx` - использование этого слова не для работы с контекстом сбивает с толку, так как он имеет другое предназначение.

сам контекст это довольно непростая парадигма (я помню очень долго не могла ее понять😳). если кратко, то он позволяет вести обработку какого-то процесса в рамках какого-то “контекста” (прошу прощения за тавтологию), почитай [как он устроен под капотом](https://habr.com/ru/post/269299/) и еще, [вот пример репозитория в котором реализовано использование контекста](https://github.com/zhashkevych/go-clean-architecture/blob/3bb8adb7e36f14ffc8d76c9325f22a5c179c9464/bookmark/repository/localcache/bookmark.go#L23) (кстати сам по себе репозиторий очень хороший, в плане реализации DI и гошных паттернов)
с пониманием теории и глядя на примеры должно появится понимание, как его можно себе завезти) если все равно останутся вопросы - ставь 1-1, разберемся)

От себя еще рекомендую почитать про [graceful shutdown](https://temofeev.ru/info/articles/artemiy-ryabinkov-avito-graceful-shutdown-v-go-servisakh-i-kak-podruzhit-ego-s-kubernetes/) и попробовать его добавить, так как без него сейчас не обходится ни один гошный сервис

2022-04-17 21:31 UTC, blattaria7 commented on internal/server/service/metrics/metrics.go
> +			return
через интерфейсы)

2022-04-17 21:44 UTC, blattaria7 commented on internal/server/server.go
> +	})
я бы рекомендовала объект ctx определить как service и при его инициализации передавать в него репозиторий. а сам сервис вот пример [как инициализируется сервер по "слоям"](https://github.com/blattaria7/go-template/blob/interfaces/cmd/main.go#L34)

Про сами интерфейсы: https://medium.com/nuances-of-programming/реализация-интерфейсов-в-golang-79fc176b481a

Прислала пример репозитория в комментарии к `ctx`. К нему еще есть [статья](https://zhashkevych.medium.com/чистая-архитектура-на-golang-cccbfdc95eba)

2022-04-25 08:48 UTC, blattaria7 approved these changes
Все отлично, ставлю аппрув!)

2022-04-25 16:37 UTC, merged